# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fa8b11004169664a5bd663c3792b35062521bb9d3c5102b461cb54c95915a7c0e7decea8563c476dcf1b5f16b30db495e0d18149f926a0686d394d87c981ed7

test:
  secret_key_base: ff55c25d875ea3c5e8c65baf78ab06c2971ffc0cb3e06c7818f6db2cefca503b1498546b6760f9192e580b8a9ec52885619b0041cc544ac2b6e61bf11654f595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
